<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>9</LangVersion>
    <IsTrimmable>false</IsTrimmable>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <AllowedReferenceRelatedFileExtensions>.pdb</AllowedReferenceRelatedFileExtensions>
    <DefineConstants>DEBUG;ENABLE_PROFILER</DefineConstants>
    <OutputPath>bin\Debug\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <AllowedReferenceRelatedFileExtensions>.none</AllowedReferenceRelatedFileExtensions>
    <DebugType>none</DebugType>
    <OutputPath>bin\Release\</OutputPath>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>Icon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Icon.ico" />
    <Content Include="Resources\Icon.ico" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\LmpMasterServer\LmpMasterServer.csproj" />
    <ProjectReference Include="..\LmpUpdater\LmpUpdater.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <PreBuildEvent>
    </PreBuildEvent>
  </PropertyGroup>
  <!-- To modify your build process, add your task inside one of the targets below and uncomment it.
       Other similar extension points exist, see Microsoft.Common.targets.
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
  </Target>
  -->
</Project>